=== rideshmaharjan/ridesh_weblab/web lab 2/question4a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="books">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="author" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="first" type="xs:string"/>
                          <xs:element name="middle" type="xs:string" minOccurs="0"/>
                          <xs:element name="last" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="title" type="titleType" default="ms"/>
                  <xs:attribute name="phone" type="xs:string" use="required"/>
                  <xs:attribute name="email" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="pageNo" type="xs:positiveInteger"/>
              <xs:element name="price">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="priceType">
                      <xs:attribute name="currency" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="NPR"/>
                            <xs:enumeration value="INR"/>
                            <xs:enumeration value="USD"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="isbn" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:unique name="uniqueISBN">
      <xs:selector xpath="book"/>
      <xs:field xpath="@isbn"/>
    </xs:unique>
  </xs:element>

  <xs:simpleType name="titleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="mr"/>
      <xs:enumeration value="ms"/>
      <xs:enumeration value="mrs"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="priceType">
    <xs:restriction base="xs:decimal">
      <xs:maxInclusive value="600"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== rideshmaharjan/ridesh_weblab/web lab 2/question4.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="question4a.xsd">
    
    <book isbn="978-1234567890">
        <title>Question3</title>
        <author title="mr" phone="9800000001" email="hellokitty@gmail.com">
            <name>
                <first>ridesh</first>
                <middle>Rai</middle>
                <last>Maharjan</last>
            </name>
        </author>
        <author phone="9800000002" email="hi@gmail.com">
            <name>
                <first>Sabin</first>
                <last>Ranabista</last>
            </name>
        </author>
        <pageNo>250</pageNo>
        <price currency="USD">500</price>
    </book>

    <book isbn="978-0987654321">
        <title>Advanced XML</title>
        <author title="mrs" phone="9800000003" email="ciao@gmail.com">
            <name>
                <first>Sukarni</first>
                <middle>Tumba</middle>
                <last>Limbu</last>
            </name>
        </author>
        <pageNo>300</pageNo>
        <price currency="NPR">599</price>
    </book>

</books>
