=== rideshmaharjan/ridesh_weblab/web lab 2/question5a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="middle" type="xs:string" minOccurs="0"/>
                    <xs:element name="last" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="email" type="emailType"/>
              <xs:element name="phone" type="phoneType"/>

              <xs:element name="address" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="type" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="permanent"/>
                            <xs:enumeration value="temporary"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>

              <xs:element name="dob">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="dobDateType">
                      <xs:attribute name="type" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="AD"/>
                            <xs:enumeration value="BS"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>

            </xs:sequence>

            <xs:attribute name="rollno" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      </xs:complexType>
      
      <xs:unique name="uniqueRollNo">
        <xs:selector xpath="student"/>
        <xs:field xpath="@rollno"/>
      </xs:unique>
  </xs:element>

  <xs:simpleType name="emailType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="phoneType">
    <xs:restriction base="xs:string">
      <xs:pattern value="98\d{8}|97\d{8}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dobDateType">
    <xs:restriction base="xs:date"/>
  </xs:simpleType>

</xs:schema>

=== rideshmaharjan/ridesh_weblab/web lab 2/question5.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="question5a.xsd">

    <student rollno="40">
        <name>
            <first>ridesh</first>
            <middle>Prasad</middle>
            <last>Maharjan</last>
        </name>
        <email>hello@gmail.com</email>
        <phone>9801234567</phone>
        <address type="permanent">Kathmandu</address>
        <address type="temporary">Lalitpur</address>
        <dob type="AD">2006-03-16</dob>
    </student>

    <student rollno="41">
        <name>
            <first>Ram</first>
            <last>Shrestha</last>
        </name>
        <email>ramshrestha1@gmail.com</email>
        <phone>9812345678</phone>
        <address type="permanent">Pokhara</address>
        <dob type="BS">2062-12-03</dob>
    </student>

</students>
