=== rideshmaharjan/ridesh_weblab/web lab 2/question7a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="movies">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Movie" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="year" type="xs:string"/>
              <xs:element name="_director">
                <xs:complexType mixed="true">
                  <xs:attribute name="name" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="comment">
                  <xs:complexType mixed="true">
                    <xs:attribute name="lang" type="xs:string" use="optional"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="newcomment" type="xs:string"/>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== rideshmaharjan/ridesh_weblab/web lab 2/question7.xml
<?xml version="1.0" encoding="UTF-8"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="question7a.xsd">

  <Movie id="m001">
    <title>Loot</title>
    <year>2012</year>
    <_director name="Nischal Basnet">Nischal Basnet</_director>
    <comment lang="en">A groundbreaking Nepali crime thriller.</comment>
    <newcomment>Popular among youth.</newcomment>
  </Movie>

  <Movie id="m002">
    <title>Chhakka Panja</title>
    <year>2016</year>
    <_director name="Deepa Shree Niraula">Deepa Shree Niraula</_director>
    <newcomment>Comedy that tackles social issues.</newcomment>
    <comment lang="en">Nepal’s highest-grossing film</comment>
  </Movie>

  <Movie id="m003">
    <title>Kagbeni</title>
    <year>2008</year>
    <_director name="Bhusan Dahal">Bhusan Dahal</_director>
    <comment>A classic Nepali thriller based on a Western tale.</comment>
    <newcomment>Beautifully shot in Mustang region.</newcomment>
  </Movie>

</movies>
